<a href="https://www.kaggle.com/code/faranakkheirandish/a1-demo-pandas-and-uci-adult-dataset?scriptVersionId=104016257" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

<center>
<img src="https://habrastorage.org/files/fd4/502/43d/fd450243dd604b81b9713213a247aa20.jpg">
    
## [mlcourse.ai](mlcourse.ai) – Open Machine Learning Course 

<center>Author: [Yury Kashnitskiy](http://yorko.github.io) <br>
Translated and edited by [Sergey Isaev](https://www.linkedin.com/in/isvforall/), [Artem Trunov](https://www.linkedin.com/in/datamove/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina/), and [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/) <br>All content is distributed under the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

# <center> Assignment #1 (demo)
## <center>  Exploratory data analysis with Pandas

**In this task you should use Pandas to answer a few questions about the [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) dataset. (You don't have to download the data – it's already here). Choose the answers in the [web-form](https://docs.google.com/forms/d/1uY7MpI2trKx6FLWZte0uVh3ULV4Cm_tDud0VDFGCOKg). This is a demo version of an assignment, so by submitting the form, you'll see a link to the solution .ipynb file.**

Unique values of all features (for more information, please see the links above):
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- `salary`: >50K,<=50K

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../input/adult.data.csv')
data.head()

   age         workclass  fnlwgt  ...   hours-per-week  native-country salary
0   39         State-gov   77516  ...               40   United-States  <=50K
1   50  Self-emp-not-inc   83311  ...               13   United-States  <=50K
2   38           Private  215646  ...               40   United-States  <=50K
3   53           Private  234721  ...               40   United-States  <=50K
4   28           Private  338409  ...               40            Cuba  <=50K

[5 rows x 15 columns]

**1. How many men and women (*sex* feature) are represented in this dataset?**

In [3]:
data.groupby(['sex']).size()

sex
Female    10771
Male      21790
dtype: int64

**2. What is the average age (*age* feature) of women?**

In [4]:
data.loc[data['sex']=='Female', 'age'].mean()

36.85823043357163

**3. What is the percentage of German citizens (*native-country* feature)?**

In [5]:
(len(data.loc[data['native-country']=='Germany']) / len(data))* 100

0.42074874850281013

**4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (*salary* feature) and those who earn less than 50K per year? **

In [6]:
# You code here
print("The mean for more than 50K: ", data.loc[data['salary']=='>50K']['age'].mean())
print("The standard deviation for more than 50K: ", data.loc[data['salary']=='>50K']['age'].std())

print("\nThe mean for less than 50K: ", data.loc[data['salary']=='<=50K']['age'].mean())
print("The standard deviation for less than 50K: ", data.loc[data['salary']=='<=50K']['age'].std())

The mean for more than 50K:  44.24984058155847
The standard deviation for more than 50K:  10.51902771985177

The mean for less than 50K:  36.78373786407767
The standard deviation for less than 50K:  14.020088490824813

**6. Is it true that people who earn more than 50K have at least high school education? (*education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* or *Doctorate* feature)**

In [7]:
# You code here
high_salary = len(data.loc[data['salary']=='>50K'])
high_salary_edu = len(data.loc[(data['salary']=='>50K') & (data['education'].isin(['Bachelors','Prof-school','Assoc-acdm','Assoc-voc','Masters','Doctorate']))])
print(high_salary==high_salary_edu)

False

**7. Display age statistics for each race (*race* feature) and each gender (*sex* feature). Use *groupby()* and *describe()*. Find the maximum age of men of *Amer-Indian-Eskimo* race.**

In [8]:
# You code here
df = pd.DataFrame(data.groupby(['race','sex']).describe())
print(df.head(5))
print(df[(df.index.get_level_values('race') == 'Amer-Indian-Eskimo') & (df.index.get_level_values('sex') == 'Male')]['age']['max'])

                              age                        ...  hours-per-week
                            count       mean        std  ...             50%   75%   max
race               sex                                   ...
Amer-Indian-Eskimo Female   119.0  37.117647  13.114991  ...            40.0  40.0  84.0
                   Male     192.0  37.208333  12.049563  ...            40.0  45.0  84.0
Asian-Pac-Islander Female   346.0  35.089595  12.300845  ...            40.0  40.0  99.0
                   Male     693.0  39.073593  12.883944  ...            40.0  45.0  99.0
Black              Female  1555.0  37.854019  12.637197  ...            40.0  40.0  99.0

[5 rows x 48 columns]
race                sex
Amer-Indian-Eskimo  Male    82.0
Name: max, dtype: float64

**8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (*marital-status* feature)? Consider as married those who have a *marital-status* starting with *Married* (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.**

In [9]:
high_income = len(data.loc[data['salary']=='>50K'])
maried_men_high_income = len(data.loc[(data['salary']=='>50K') & (data['sex']=='Male') & (data['marital-status'].str.contains('Married'))])
single_men_high_income = high_income - maried_men_high_income
print("The portion of maried men who are earning a lot: ", maried_men_high_income)
print("The portion of single men who are earning a lot: ", single_men_high_income)

The portion of maried men who are earning a lot:  5965
The portion of single men who are earning a lot:  1876

**9. What is the maximum number of hours a person works per week (*hours-per-week* feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?**

In [10]:
max_hours = data['hours-per-week'].max()
num_max_hours = data.loc[data['hours-per-week'] ==max_hours].size
pct_high_income= data.loc[(data['hours-per-week'] ==max_hours) & (data['salary']=='>50K')].size
print("The max number of hourse a person works per week: {0}\nThe number of people works {0} hourse per week: {1}\nThe percentage of those who earn alot: {2:.2f}%"
      .format(max_hours, num_max_hours,(pct_high_income / num_max_hours)*100 ))

The max number of hourse a person works per week: 99
The number of people works 99 hourse per week: 1275
The percentage of those who earn alot: 29.41%

**10. Count the average time of work (*hours-per-week*) for those who earn a little and a lot (*salary*) for each country (*native-country*). What will these be for Japan?**

In [11]:
print('The average time of work (hours-per-week) for those who earn a lot ')
print(data.query('salary == ">50K"').groupby(['native-country'])['hours-per-week'].mean())
print('\n\nThe average time of work (hours-per-week) for those who earn a little ')
print(data.query('salary == "<=50K"').groupby(['native-country'])['hours-per-week'].mean())

The average time of work (hours-per-week) for those who earn a lot
native-country
?                     45.547945
Cambodia              40.000000
Canada                45.641026
China                 38.900000
Columbia              50.000000
Cuba                  42.440000
Dominican-Republic    47.000000
Ecuador               48.750000
El-Salvador           45.000000
England               44.533333
France                50.750000
Germany               44.977273
Greece                50.625000
Guatemala             36.666667
Haiti                 42.750000
Honduras              60.000000
Hong                  45.000000
Hungary               50.000000
India                 46.475000
Iran                  47.500000
Ireland               48.000000
Italy                 45.400000
Jamaica               41.100000
Japan                 47.958333
Laos                  40.000000
Mexico                46.575758
Nicaragua             37.500000
Peru                  40.000000
Philippines           43.032787
Poland                39.000000
Portugal              41.500000
Puerto-Rico           39.416667
Scotland              46.666667
South                 51.437500
Taiwan                46.800000
Thailand              58.333333
Trinadad&Tobago       40.000000
United-States         45.505369
Vietnam               39.200000
Yugoslavia            49.500000
Name: hours-per-week, dtype: float64


The average time of work (hours-per-week) for those who earn a little
native-country
?                             40.164760
Cambodia                      41.416667
Canada                        37.914634
China                         37.381818
Columbia                      38.684211
Cuba                          37.985714
Dominican-Republic            42.338235
Ecuador                       38.041667
El-Salvador                   36.030928
England                       40.483333
France                        41.058824
Germany                       39.139785
Greece                        41.809524
Guatemala                     39.360656
Haiti                         36.325000
Holand-Netherlands            40.000000
Honduras                      34.333333
Hong                          39.142857
Hungary                       31.300000
India                         38.233333
Iran                          41.440000
Ireland                       40.947368
Italy                         39.625000
Jamaica                       38.239437
Japan                         41.000000
Laos                          40.375000
Mexico                        40.003279
Nicaragua                     36.093750
Outlying-US(Guam-USVI-etc)    41.857143
Peru                          35.068966
Philippines                   38.065693
Poland                        38.166667
Portugal                      41.939394
Puerto-Rico                   38.470588
Scotland                      39.444444
South                         40.156250
Taiwan                        33.774194
Thailand                      42.866667
Trinadad&Tobago               37.058824
United-States                 38.799127
Vietnam                       37.193548
Yugoslavia                    41.600000
Name: hours-per-week, dtype: float64